# Site settings
title: Niong
email: zhuxiong001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  废材大二 | 努力朝coder前进中 | 内在无趣
baseurl: "" # the subpath of your site, e.g. /blog/
url:“www.niong.xyz”# the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Xcent-xl
disqus: 

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html