# Site settings
title: test blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  个人博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Xcent-xl
disqus: 

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html